name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Enabling caching of previously compiled objects
        uses: actions/cache@v3
        with:
          key: build-cache
          path: |
            bin/CMakeFiles
            bin/lib
            bin/test/CMakeFiles
            bin/test/googlemock
            bin/test/googletest
            bin/.ninja_deps
            bin/.ninja_log
            bin/build.ninja
            bin/CMakeCache.txt

      # Install latest CMake and Ninja.
      - uses: lukka/get-cmake@latest
      # Or pin to a specific CMake version:
      # lukka/get-cmake@v3.21.2

      - name: Run CMake consuming CMakePresets.json and vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: 'buildAndTest'
